mongodb:
  image: mongo
  expose:
   - "27017"
  ports:
   - "27017:27017"
  command: /entrypoint.sh --smallfiles

comment-server:
  build: .
  links:
   - mongodb
  expose:
   - "8080"
  ports:
   - "8080:8080"
  environment:
   - MONGODB_ADDR=mongodb/test
   - LISTEN_HOST=0.0.0.0
   - LISTEN_PORT=8080
   - SERVE_PATH=/usr/src/app/out/client
   
